### ISSUE TITLE
Write a custom frontend for Timeout

### ISSUE THREAD

**Issue by matiasilva** [SRCF/projects#11]
## Project/idea summary

Write a custom frontend with features that are specific to Cambridge and most sought after by societies, groups, staff and teachers. This is written in Python and uses the Flask framework. The web app would feature things like user management, account creation, Raven integration, custom rooms, group pages, etc.

### Repository

https://github.com/SRCF/lightbluetent/

Talk to Matias (mw781@srcf.net  or hamlam in the discord) for more information on this project.

## Motivation

We use Greenlight for timeout.srcf.net. This is a good frontend and easy to use but it comes with several challenges:

* non standard practices and "cursed" code
* nobody understands ruby, making any development or further customization difficult
* it is generic; with features we don't need and lacking features we want

## Alternatives considered

For technologies, we chose Flask for its simplicity and because control panel uses it. For other solutions, I believe there are no other viable alternatives.

**Comment by edwinbalani** [comment]
Timeout has been retired, closing.
